// Generated by @pragmatic-tech-ai/todl read-client codegen. Do not edit.
import { ModelDataSource, ReflectedEntity } from "../../../index.js";
import type { EntityReader, IModelDataConnector, InstanceDescriptor, NodeId, Scalar, TodlDocument } from "../../../index.js";

export class TechCatalog extends ModelDataSource {
  constructor(connector?: IModelDataConnector) {
    super(connector);
    this.modelName = "tech-catalog";
    this.modelVersion = "0.0.0";
  }

  static fromJSON(doc: TodlDocument): TechCatalog {
    const client = new TechCatalog();
    client.loadDocument(doc);
    return client;
  }

  protected override createEntity(reader: EntityReader): ReflectedEntity {
    switch (reader.concept) {
      case "billing": return new Billing(this, reader);
      case "location": return new Location(this, reader);
      case "technology": return new Technology(this, reader);
      default: return super.createEntity(reader);
    }
  }

  get billings(): readonly Billing[] {
    return this.instancesOf("billing") as readonly Billing[];
  }

  get locations(): readonly Location[] {
    return this.instancesOf("location") as readonly Location[];
  }

  get technologies(): readonly Technology[] {
    return this.instancesOf("technology") as readonly Technology[];
  }

  get stack(): readonly Technology[] {
    return this.termsOf("stack") as readonly Technology[];
  }

  billing(id: string, fields: {
    label: string;
  }): InstanceDescriptor {
    const scalars = new Map<string, Scalar>();
    const refs = new Map<string, readonly NodeId[]>();
    scalars.set("label", fields.label);
    return { concept: "billing", id, scalars, refs };
  }

  location(id: string, fields: {
    label: string;
  }): InstanceDescriptor {
    const scalars = new Map<string, Scalar>();
    const refs = new Map<string, readonly NodeId[]>();
    scalars.set("label", fields.label);
    return { concept: "location", id, scalars, refs };
  }

  technology(id: string, fields: {
    label: string;
    availableIn?: readonly Location[];
    billing?: Billing;
  }): InstanceDescriptor {
    const scalars = new Map<string, Scalar>();
    const refs = new Map<string, readonly NodeId[]>();
    scalars.set("label", fields.label);
    if (fields.availableIn !== undefined) refs.set("availableIn", fields.availableIn.map((e) => e.id));
    if (fields.billing !== undefined) refs.set("billing", [fields.billing.id]);
    return { concept: "technology", id, scalars, refs };
  }
}

export class Billing extends ReflectedEntity {
  get label(): string { return this.field("label") as string; }
}

export class Location extends ReflectedEntity {
  get label(): string { return this.field("label") as string; }
}

export class Technology extends ReflectedEntity {
  get label(): string { return this.field("label") as string; }
  get availableIn(): readonly Location[] { return this.refs("availableIn") as readonly Location[]; }
  get billing(): Billing | undefined { return this.ref("billing") as Billing | undefined; }
}
