// Generated by @pragmatic-tech-ai/todl read-client codegen. Do not edit.
import { FrozenRepository, EntityBase } from "../../../index.js";
import type { InstanceDescriptor, NodeId, Scalar } from "../../../index.js";

export class TechCatalog extends FrozenRepository {
  protected override createEntity(id: string): EntityBase {
    switch (this.resolve(id)?.type) {
      case "billing": return new Billing(this, id);
      case "location": return new Location(this, id);
      case "technology": return new Technology(this, id);
      default: return super.createEntity(id);
    }
  }

  get billings(): readonly Billing[] {
    return this.instancesOf("billing").filter((id) => !this.isClass(id)).map((id) => this.entity(id) as Billing);
  }

  get locations(): readonly Location[] {
    return this.instancesOf("location").filter((id) => !this.isClass(id)).map((id) => this.entity(id) as Location);
  }

  get technologies(): readonly Technology[] {
    return this.instancesOf("technology").filter((id) => !this.isClass(id)).map((id) => this.entity(id) as Technology);
  }

  get stack(): readonly Technology[] {
    return this.termsOf("stack").map((id) => this.entity(id) as Technology);
  }

  billing(id: string, fields: {
    label: string;
  }): InstanceDescriptor {
    const scalars = new Map<string, Scalar>();
    const refs = new Map<string, readonly NodeId[]>();
    scalars.set("label", fields.label);
    return { concept: "billing", id, scalars, refs };
  }

  location(id: string, fields: {
    label: string;
  }): InstanceDescriptor {
    const scalars = new Map<string, Scalar>();
    const refs = new Map<string, readonly NodeId[]>();
    scalars.set("label", fields.label);
    return { concept: "location", id, scalars, refs };
  }

  technology(id: string, fields: {
    label: string;
    availableIn?: readonly Location[];
    billing?: Billing;
  }): InstanceDescriptor {
    const scalars = new Map<string, Scalar>();
    const refs = new Map<string, readonly NodeId[]>();
    scalars.set("label", fields.label);
    if (fields.availableIn !== undefined) refs.set("availableIn", fields.availableIn.map((e) => e.id));
    if (fields.billing !== undefined) refs.set("billing", [fields.billing.id]);
    return { concept: "technology", id, scalars, refs };
  }
}

export class Billing extends EntityBase {
  get label(): string { return this.field("label") as string; }
}

export class Location extends EntityBase {
  get label(): string { return this.field("label") as string; }
}

export class Technology extends EntityBase {
  get label(): string { return this.field("label") as string; }
  get availableIn(): readonly Location[] { return this.refs("availableIn") as Location[]; }
  get billing(): Billing | undefined { return this.ref("billing") as Billing | undefined; }
}
