/**
 * Produces `generated/data.ts`, which instantiates the DTO (`generated/model.ts`)
 * from the document the host injects as `window.__TODL_APP__`. Needs no model
 * compile: the DTO class name derives from the manifest via `AppNaming`, using
 * the same `id ?? name` source as `DtoGenerator`. Overwritten so it tracks the DTO.
 */

import { WritePolicy } from "./project-content-generator.js";
import { WritePolicyWriter } from "./write-policy-writer.js";
import { AppNaming } from "./app-naming.js";
import { GeneratorTrigger, type IProjectContentGenerator, type GeneratorContext, type GeneratorResult } from "./project-content-generator.js";

export class ModelInstanceGenerator implements IProjectContentGenerator
{
    private static readonly GeneratorId = "model-data";
    private static readonly Display = "Model data";
    private static readonly OutputFile = "generated/data.ts";
    private static readonly Header = "// Generated by @pragmatic-tech-ai/todl. Do not edit.";
    private static readonly AppGlobal = "__TODL_APP__";
    private static readonly ModelImportPath = "./model.js";

    public readonly Id = ModelInstanceGenerator.GeneratorId;
    public readonly DisplayName = ModelInstanceGenerator.Display;
    public readonly Produces: readonly string[] = [ModelInstanceGenerator.OutputFile];
    public readonly Triggers: readonly GeneratorTrigger[] = [GeneratorTrigger.ProjectCreated, GeneratorTrigger.ReferencesChanged];
    public readonly WritePolicy = WritePolicy.Overwrite;

    public async Generate(ctx: GeneratorContext): Promise<GeneratorResult>
    {
        const dto = AppNaming.DtoClass(ctx.Manifest.id ?? ctx.Manifest.name);
        const body =
            `${ModelInstanceGenerator.Header}\n` +
            `import { ${dto} } from "${ModelInstanceGenerator.ModelImportPath}";\n` +
            `export const model = ${dto}.fromJSON((window as any).${ModelInstanceGenerator.AppGlobal});\n`;
        const wrote = await WritePolicyWriter.Write(ctx.Project, ModelInstanceGenerator.OutputFile, body, this.WritePolicy);
        return wrote ? { Written: [ModelInstanceGenerator.OutputFile], Skipped: [] } : { Written: [], Skipped: [ModelInstanceGenerator.OutputFile] };
    }
}
