import { ServiceKey, type IServiceProvider, type IStorage } from '@pragmatic-tech-ai/todl-runtime'
import { check, checkAgainst } from '../../api.js'
import { toJSON, type TodlDocument } from '../../emit/json.js'
import { Severity } from '../../diagnostics/diagnostic.js'
import { compilePackage, PackageKind } from '../../publish/publish.js'
import { BlobPackageStore } from '../../publish/stores.js'
import { projectAnnotations } from '../../publish/reflect.js'
import {
    PROJECT_MANIFEST_FILENAME,
    ProducerKind,
    type IPresentationProjectFactory,
    type IPublishableProjectFactory,
    type IVersionedProjectFactory,
    type ProjectFileFormat,
    type ProjectManifestEnvelope,
    type PublishResult,
} from './project-factory.js'
import { type IProducerProjectFactory } from './producer-project-factory.js'
import { TodlProjectFactory, CLAUDE_DIR, CLAUDE_MD_FILENAME, type ScaffoldFile } from './todl-project-factory.js'
import { type Project, ProjectNodeKind } from './project.js'
import { TodlSources } from './todl-sources.js'
import { StoragePackageSink } from './storage-package-sink.js'
import { PresentationModel } from './presentation-model.js'
import { PresentationBakerKey } from './presentation-baker.js'
import { ProducerBackendsKey } from './producer-backends.js'
import { type MetaModelManifestFile } from './meta-model-manifest.js'
import { META_MODEL_CLAUDE_ROOT, META_MODEL_GUIDE, META_MODEL_NEW_CONCEPT } from './scaffold.generated.js'

// The 'meta-model' project type's factory. It owns the project lifecycle; the `.todl`
// FILE format is edited by its document factory (resolved by extension) — editors own
// files, this factory owns the project.
//
// It is publishable (IPublishableProjectFactory): publish validates every `.todl` with
// TODL's check(), and — if clean — writes the compiled TodlDocument JSON plus the raw
// sources into the shared meta-models backend under `<id>/<modelVersion>/`, where other
// project types consume it. The presentation bake (mural-coupled) and the backend
// resolution (app-coupled) are reached through the IPresentationBaker / IProducerBackends
// seams, resolved from the container — todl stays free of both. All persistence flows
// through the project's rooted IStorage.
interface MetaModelManifest extends ProjectManifestEnvelope
{
    id: string             // stable publish identity, defaults to slugify(name)
    modelVersion: string   // published version, defaults to '0.1.0'
}

export class MetaModelProjectFactory extends TodlProjectFactory
    implements IPublishableProjectFactory, IPresentationProjectFactory, IProducerProjectFactory, IVersionedProjectFactory
    {
    public static readonly Key = new ServiceKey<MetaModelProjectFactory>('MetaModelProjectFactory')
    public static readonly ProjectType = 'meta-model'

    // The autogenerated presentation dictionary. Only this file is ever written by the
    // factory (author overrides live under presentation/*.mu).
    private static readonly PRESENTATION_FILE = 'presentation.generated.mu'
    private static readonly DICT_NAME = 'MetaModelPresentation'
    private static readonly ICON_PREFIX = 'mm:'
    private static readonly PACKAGE_NODE = 'package'

    public readonly typeId = MetaModelProjectFactory.ProjectType
    public readonly title = 'Meta-model Project'
    public readonly description = 'Author and validate TODL meta-model definitions.'

    public readonly formats: readonly ProjectFileFormat[] = [
        { extension: '.todl', kind: ProjectNodeKind.Todl, displayName: 'TODL Definition' },
    ]

    public readonly producerKind = ProducerKind.MetaModel

    constructor(provider: IServiceProvider) { super(provider) }

    protected buildManifest(name: string): ProjectManifestEnvelope
    {
        const manifest: MetaModelManifest = {
            type: MetaModelProjectFactory.ProjectType, name, version: 1,
            id: MetaModelProjectFactory.slugify(name), modelVersion: '0.1.0',
        }
        return manifest
    }

    // The meta-model's own scaffold (its CLAUDE.md + guide + /new-concept); the shared
    // TODL manual + rules are added by the base.
    protected scaffoldContributions(): readonly ScaffoldFile[]
    {
        return [
            { path: CLAUDE_MD_FILENAME, content: META_MODEL_CLAUDE_ROOT },
            { path: `${CLAUDE_DIR}/meta-model-guide.md`, content: META_MODEL_GUIDE },
            { path: `${CLAUDE_DIR}/commands/new-concept.md`, content: META_MODEL_NEW_CONCEPT },
        ]
    }

    public async getVersion(storage: IStorage): Promise<string>
    {
        const manifest = JSON.parse(await storage.ReadText(PROJECT_MANIFEST_FILENAME)) as MetaModelManifest
        return manifest.modelVersion
    }

    public async setVersion(storage: IStorage, version: string): Promise<void>
    {
        const manifest = JSON.parse(await storage.ReadText(PROJECT_MANIFEST_FILENAME)) as MetaModelManifest
        manifest.modelVersion = version
        await storage.WriteText(PROJECT_MANIFEST_FILENAME, JSON.stringify(manifest, null, 2))
    }

    // Compile every `.todl` into the base document, exactly as publish does. A meta-model
    // has no bases of its own, so callers pass `bases` (usually []).
    public async compileToDocument(
        storage: IStorage,
        bases: TodlDocument[],
        _provider: IServiceProvider,
    ): Promise<{ doc: TodlDocument; problems: string[] }>
    {
        const sources = await TodlSources.Collect(storage)
        const { model, diagnostics } = checkAgainst(bases, sources)
        const problems = diagnostics
            .filter((d) => d.severity === Severity.Error)
            .map((d) => d.message)
        return { doc: toJSON(model), problems }
    }

    // Validate every `.todl` together; if clean, emit the compiled model + copy the
    // sources into the meta-models backend under `<id>/<modelVersion>/`.
    public async publish(_project: Project, storage: IStorage, provider: IServiceProvider): Promise<PublishResult>
    {
        const manifest = JSON.parse(await storage.ReadText(PROJECT_MANIFEST_FILENAME)) as MetaModelManifest
        const sources = await TodlSources.Collect(storage)
        if (sources.length === 0) return { ok: false, message: 'Nothing to publish — the project has no .todl files.' }

        const outcome = compilePackage([], sources, {
            id: manifest.id,
            version: manifest.modelVersion,
            name: manifest.name ?? manifest.id,
        })
        if (!outcome.ok || outcome.package === undefined)
            return { ok: false, message: `Publish blocked: ${outcome.errors.length} error(s). Fix them first.` }
        const pkg = outcome.package
        const doc = pkg.document

        // Assign + write mural resource keys onto icon apps before either the
        // presentation or model.json is written — pkg.document is the same object
        // BlobPackageStore persists, so the key reaches model.json.
        PresentationModel.StampResourceKeys(doc)

        const dest = provider.getRequired(ProducerBackendsKey).Backend(PackageKind.MetaModel)
        const base = `${manifest.id}/${manifest.modelVersion}`

        // Bake the presentation first — a missing icon blocks the publish before
        // anything is written to the backend.
        const pres = await provider.getRequired(PresentationBakerKey).Bake(storage, dest, base, doc, {
            dictName: MetaModelProjectFactory.DICT_NAME, iconPrefix: MetaModelProjectFactory.ICON_PREFIX,
        })
        if (!pres.ok)
            return { ok: false, message: `Publish blocked: missing icon file(s): ${pres.missing.join(', ')}.` }

        // model.json + src/ written by TODL's BlobPackageStore (the publish spine).
        await new BlobPackageStore(new StoragePackageSink(dest)).persist(pkg)
        // Ship a thin package descriptor (identity + package-level annotations).
        const manifestFile: MetaModelManifestFile = {
            id: manifest.id, version: manifest.modelVersion, name: manifest.name ?? manifest.id,
            annotations: projectAnnotations(doc, MetaModelProjectFactory.PACKAGE_NODE),
        }
        await dest.WriteText(`${base}/manifest.json`, JSON.stringify(manifestFile, null, 2))
        // Keep the project's presentation dictionary current with what was published.
        await this.writePresentation(storage, doc, true)
        return {
            ok: true,
            message: `Published ${manifest.id}@${manifest.modelVersion} (${sources.length} file(s), `
                + `presentation: ${pres.icons} icon(s)).`,
        }
    }

    // Capability entry point (the "Generate Presentation" command): compile the project's
    // .todl to a model, then write the presentation dictionary. No .todl → no-op; a TODL
    // error → leave the file untouched (the Problems dock already surfaces the errors).
    public async regeneratePresentation(storage: IStorage, colored: boolean): Promise<void>
    {
        const sources = await TodlSources.Collect(storage)
        if (sources.length === 0) return
        const { model, diagnostics } = check(sources)
        if (diagnostics.some((d) => d.severity === Severity.Error)) return
        await this.writePresentation(storage, toJSON(model), colored)
    }

    // Write presentation.generated.mu (icons-only assets dict) from an already-compiled
    // document. `colored` selects colorful vs monochrome icon includes.
    private async writePresentation(storage: IStorage, doc: TodlDocument, colored: boolean): Promise<void>
    {
        await storage.WriteText(
            MetaModelProjectFactory.PRESENTATION_FILE,
            PresentationModel.GenerateAssets(doc, MetaModelProjectFactory.DICT_NAME, colored))
    }

    private static slugify(name: string): string
    {
        return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'meta-model'
    }
}
