// presentation-model.ts — pure emitter for a producer's presentation resource
// dictionary + the icon-key derivation both the generator and the (app-side) baker
// share. No I/O, no mural import; deterministic text only. Static methods on one type
// rather than free functions — the OOP counterpart of the former functional module.

import { projectAnnotations } from '../../publish/reflect.js'
import { type TodlDocument, type JsonNode } from '../../emit/json.js'

// The ontology-tier typeOf values presented as first-class entities. `field` (concept
// attributes) is intentionally excluded.
export enum OntologyKind
{
    Concept = 'concept',
    Relationship = 'relationship',
    Taxonomy = 'taxonomy',
    Viewpoint = 'viewpoint',
    Primitive = 'primitive',
}

const ONTOLOGY_KINDS = new Set<string>(Object.values(OntologyKind))

export interface PresentationFacets { icon?: string; label: string }

export class PresentationModel
{
    // Ontology-tier nodes that are presentable entities (concept/relationship/
    // taxonomy/primitive), in model order.
    public static OntologyEntities(model: TodlDocument): JsonNode[]
    {
        return model.nodes.filter((n) => n.tier === 'Ontology' && ONTOLOGY_KINDS.has(n.metaKind ?? ''))
    }

    // Instance-tier `class` nodes — a taxonomy term (staged with `class: true`) or a
    // `class` declaration. Presented as first-class templates so a term's annotation
    // icon/label renders. In model order.
    public static ClassEntities(model: TodlDocument): JsonNode[]
    {
        return model.nodes.filter((n) => n.tier === 'Instance' && n.isClass)
    }

    // Distinct icon paths across every node, sorted — the SVGs the generated dictionary
    // `include`s. Icons are sourced solely from `<x>@icon` annotation application nodes
    // (`annotate icon { path }`); the legacy `attrs.icon` field form was removed.
    public static DistinctIcons(model: TodlDocument): string[]
    {
        const set = new Set<string>()
        for (const n of model.nodes)
        {
            if (n.type === 'icon')
            {
                const path = n.attrs['path']
                if (typeof path === 'string' && path.length > 0) set.add(path)
            }
        }
        return [...set].sort()
    }

    // Emit the presentation ASSET dictionary: one `include` per distinct icon plus a
    // reserved seam for future base64 embedded content. No DataTemplates — every entity
    // renders through the one default template. `colored` picks the icon mode. This is
    // an inspection artifact — nothing consumes the generated file at runtime.
    public static GenerateAssets(doc: TodlDocument, dictName: string, colored: boolean): string
    {
        const includes = [...PresentationModel.AssignResourceKeys(doc)].map(([p, k]) => PresentationModel.IncludeLine(p, k, colored))
        return [
            '// presentation.generated.mu — AUTOGENERATED. Do not edit.',
            '// Regenerated from the compiled model. Author templates live in presentation/*.mu.',
            '',
            `resources ${dictName} {`,
            '',
            '    // --- Icons: one geometry per distinct icon referenced by the model. ---',
            ...includes,
            '',
            '    // --- Embedded content (base64) — reserved for future assets. ---',
            '}',
            '',
        ].join('\n')
    }

    // A raster (bitmap) icon path — baked as a BitmapImage vs an SVG IconDefinition.
    public static IsRasterIcon(path: string): boolean
    {
        return /\.(png|jpe?g|webp|gif)$/i.test(path)
    }

    // One `include` line for a presentation `resources { … }` body (4-space indented).
    // When `colored`, an SVG icon uses the `colored` keyword so the compiler bakes a
    // COLORED IconDefinition; otherwise a plain include → monochrome geometry. Raster
    // icons are always a plain include (→ a BitmapImage); the keyword is SVG-only.
    public static IncludeLine(path: string, key: string, colored: boolean): string
    {
        const keyword = colored && !PresentationModel.IsRasterIcon(path) ? 'colored ' : ''
        return `    include ${keyword}"${path}" as ${key}`
    }

    // "resources/actor-internal.svg" → "mm_icon_actor_internal". Strips the directory +
    // extension, lowercases, and replaces every non-identifier run with a single '_'.
    public static IconKey(path: string): string
    {
        const stem = path.replace(/^.*\//, '').replace(/\.[^.]+$/, '')
        const slug = stem.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '')
        return `mm_icon_${slug}`
    }

    // Assign every distinct icon path a UNIQUE mural resource key. When two paths share
    // a stem the second and later collisions are suffixed _2, _3, … in sorted-path order.
    // A pure function of the doc's icon paths; iteration order follows DistinctIcons.
    public static AssignResourceKeys(doc: TodlDocument): Map<string, string>
    {
        const out = new Map<string, string>()
        const used = new Map<string, number>()
        for (const path of PresentationModel.DistinctIcons(doc))
        {
            const base = PresentationModel.IconKey(path)
            const n = used.get(base) ?? 0
            used.set(base, n + 1)
            out.set(path, n === 0 ? base : `${base}_${n + 1}`)
        }
        return out
    }

    // The unique resource key for one icon path in this doc. Falls back to the base
    // IconKey for a path not among the doc's icons (should not happen in practice).
    public static ResourceKeyFor(doc: TodlDocument, path: string): string
    {
        return PresentationModel.AssignResourceKeys(doc).get(path) ?? PresentationModel.IconKey(path)
    }

    // Write the assigned resource key onto each icon application node in place — the
    // "write-back" that lands in the compiled artifact (model.json). Only annotation
    // application nodes (typeOf 'icon' carrying a `path`) are stamped. Called over
    // pkg.document before persist, so the stamped key reaches model.json.
    public static StampResourceKeys(doc: TodlDocument): void
    {
        const keys = PresentationModel.AssignResourceKeys(doc)
        for (const n of doc.nodes)
        {
            if (n.type !== 'icon') continue
            const attrs = n.attrs as Record<string, unknown>
            const path = attrs['path']
            if (typeof path !== 'string' || path.length === 0) continue
            const key = keys.get(path)
            if (key !== undefined) attrs['key'] = key
        }
    }

    // "app-component" → "App Component". Splits on '-'/'.'/'_' and title-cases each
    // word. Used as the fallback label when an entity declares no attrs.label.
    public static Humanize(id: string): string
    {
        return id.split(/[-._]/).filter(Boolean)
            .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
            .join(' ')
    }

    // entityKey (prefix + id) → icon resource key, for every presentable entity that
    // resolves an icon. `prefix` is '' (library keyspace) or 'mm:' (meta-model
    // keyspace). Icon-less entities are omitted. Emitted at publish time into
    // icon-index.json so load never re-derives keys.
    public static BuildIconIndex(doc: TodlDocument, prefix: string): Map<string, string>
    {
        const out = new Map<string, string>()
        for (const n of [...PresentationModel.OntologyEntities(doc), ...PresentationModel.ClassEntities(doc)])
        {
            const { icon } = PresentationModel.ResolveFacets(n, projectAnnotations(doc, n.id))
            if (icon === undefined) continue
            out.set(prefix + n.id, PresentationModel.ResourceKeyFor(doc, icon))
        }
        return out
    }

    // Resolves the well-known presentation facets for a node. `annotations` is the
    // projected bag for that node (projectAnnotations output). The icon comes solely
    // from the `icon` annotation; the label stays attr-primary, falling back through
    // the annotation to Humanize(id).
    public static ResolveFacets(node: JsonNode, annotations: Record<string, Record<string, unknown>>): PresentationFacets
    {
        const annIcon = annotations['icon']?.['path']
        const icon = (typeof annIcon === 'string' && annIcon.length > 0) ? annIcon : undefined

        const attrLabel = node.attrs['label']
        const annLabel = annotations['label']?.['text']
        const label = typeof attrLabel === 'string' ? attrLabel
            : typeof annLabel === 'string' ? annLabel
                : PresentationModel.Humanize(node.id)

        const facets: PresentationFacets = { label }
        if (icon !== undefined) facets.icon = icon
        return facets
    }
}
