// Emits a self-contained, runnable package from a compiled application Repository:
// the reused read-client accessor class over the shared ontology, one embedded
// document shard per model, and an AppRegistry factory that wires each model
// behind a BundledModelDataConnector and designates the root. The emitted OUTPUT
// follows the read-client generated-code style, not house style.

import { Repository } from "../compiler-services/model/model.js";
import { toJSON, type TodlDocument } from "../compiler-services/emit/json.js";
import type { NodeId } from "../compiler-services/model/graph.js";
import { ApplicationRootResolver } from "../model-data/application-root-resolver.js";
import { ModelShardExtractor } from "../model-data/model-shard-extractor.js";
import { generateReadClient } from "./read-client.js";
import { pascalCase } from "./naming.js";

export interface ModelPackageOptions
{
    /** Artifact id (kebab); becomes the PascalCase data-access class name. */
    name: string;
    /** Import specifier for the todl runtime. Defaults to "@pragmatic-tech-ai/todl". */
    importSpecifier?: string;
    /** Name of the emitted registry-factory class. Defaults to "AppRegistry". */
    registryClassName?: string;
}

export class ModelPackageGenerator
{
    private static readonly DefaultRuntimeImport = "@pragmatic-tech-ai/todl";
    private static readonly DefaultRegistryClassName = "AppRegistry";
    private static readonly ShardPrefix = "SHARD_";
    private static readonly HeaderComment = "// Generated by @pragmatic-tech-ai/todl application codegen. Do not edit.";
    private static readonly NotAnApplicationMessage =
        "ModelPackageGenerator.Generate requires an application root; the model has no `entrypoint` designation.";

    public static Generate(repo: Repository, options: ModelPackageOptions): string
    {
        const runtimeImport = options.importSpecifier ?? ModelPackageGenerator.DefaultRuntimeImport;
        const registryClass = options.registryClassName ?? ModelPackageGenerator.DefaultRegistryClassName;
        const accessorClass = pascalCase(options.name);

        const doc = toJSON(repo);
        const rootId = ApplicationRootResolver.Resolve(doc);
        if (rootId === undefined)
        {
            throw new Error(ModelPackageGenerator.NotAnApplicationMessage);
        }
        const models = [...ModelShardExtractor.ModelsOf(doc)].sort();

        const header = ModelPackageGenerator.EmitHeader(runtimeImport);
        const body = generateReadClient(repo, { name: options.name, importSpecifier: runtimeImport, omitHeader: true });
        const shards = models.map((m) => ModelPackageGenerator.EmitShard(m, doc)).join("\n");
        const factory = ModelPackageGenerator.EmitFactory(registryClass, accessorClass, models, rootId);

        return [header, body.trimEnd(), shards, factory].join("\n\n") + "\n";
    }

    private static EmitHeader(runtimeImport: string): string
    {
        return (
            ModelPackageGenerator.HeaderComment + "\n" +
            `import { ModelDataSource, ReflectedEntity, ModelRegistry, BundledModelDataConnector } from "${runtimeImport}";\n` +
            `import type { EntityReader, IModelDataConnector, InstanceDescriptor, NodeId, Scalar, TodlDocument } from "${runtimeImport}";`
        );
    }

    private static EmitShard(modelId: NodeId, doc: TodlDocument): string
    {
        const shard = ModelShardExtractor.Extract(doc, modelId);
        return `const ${ModelPackageGenerator.SlugFor(modelId)}: TodlDocument = ${JSON.stringify(shard)};`;
    }

    private static EmitFactory(
        registryClass: string,
        accessorClass: string,
        models: readonly NodeId[],
        rootId: NodeId,
    ): string
    {
        const registers = models
            .map((m) => `    registry.Register("${m}", new ${accessorClass}(new BundledModelDataConnector(${ModelPackageGenerator.SlugFor(m)})));`)
            .join("\n");
        return (
            `export class ${registryClass} {\n` +
            `  static Create(): ModelRegistry {\n` +
            `    const registry = new ModelRegistry();\n` +
            `${registers}\n` +
            `    registry.SetRoot("${rootId}");\n` +
            `    return registry;\n` +
            `  }\n` +
            `}`
        );
    }

    private static SlugFor(modelId: NodeId): string
    {
        return ModelPackageGenerator.ShardPrefix + String(modelId).replace(/[^A-Za-z0-9]/g, "_").toUpperCase();
    }
}
