/**
 * Read-client codegen (design spec §6, Component C). Reflects a resolved
 * {@link Repository} (concepts, taxonomies, `effectiveSchema`) and emits a `.ts`
 * source with a typed package class (per-concept + per-taxonomy collection
 * accessors, routed construction) and one typed entity class per concept
 * (scalar + reference getters). Output is deterministic — everything sorted by id.
 */

import { MetaKind } from "../model/kinds.js";
import { Cardinality, type NodeId } from "../model/graph.js";
import { Repository } from "../model/model.js";
import { pascalCase, camelCase, pluralize, allocateNames } from "./naming.js";

export interface ReadClientOptions
{
  /** Artifact id (kebab); becomes the PascalCase package class name. */
  name: string;
  /** Import module specifier for the todl runtime. Defaults to the package name. */
  importSpecifier?: string;
}

/** True when `typeId` names a concept or taxonomy (→ reference); false for a primitive. */
export function isReferenceType(repo: Repository, typeId: string): boolean
{
  const kind = repo.resolve(typeId)?.metaKind;
  return kind === MetaKind.Concept || kind === MetaKind.Taxonomy;
}

interface RefMember
{
  name: string;
  targetPascal: string;
  many: boolean;
}

function scalarTsType(typeId: string): string
{
  if (typeId === "integer" || typeId === "number") return "number";
  if (typeId === "boolean") return "boolean";
  return "string";
}

function isMany(cardinality: Cardinality): boolean
{
  return cardinality === Cardinality.Many || cardinality === Cardinality.OneOrMore;
}

/** The PascalCase entity type a reference member resolves to. */
function targetPascal(repo: Repository, typeId: string): string
{
  if (repo.resolve(typeId)?.metaKind === MetaKind.Taxonomy)
  {
    return pascalCase(repo.represents(typeId)[0] ?? typeId);
  }
  return pascalCase(typeId);
}

export function generateReadClient(repo: Repository, options: ReadClientOptions): string
{
  const importSpecifier = options.importSpecifier ?? "@pragmatic-tech-ai/todl";

  const concepts = repo
    .allNodes()
    .filter((n) => n.metaKind === MetaKind.Concept)
    .map((n) => n.id)
    .sort();
  const taxonomies = repo
    .allNodes()
    .filter((n) => n.metaKind === MetaKind.Taxonomy)
    .map((n) => n.id)
    .sort();

  // Force the collision check across all generated entity-class names.
  allocateNames(concepts, pascalCase);

  const header =
    `// Generated by @pragmatic-tech-ai/todl read-client codegen. Do not edit.\n` +
    `import { FrozenRepository, EntityBase } from "${importSpecifier}";\n` +
    `import type { InstanceDescriptor, NodeId, Scalar } from "${importSpecifier}";`;

  const packageClass = emitPackageClass(pascalCase(options.name), concepts, taxonomies, repo);
  const entityClasses = concepts.map((c) => emitEntityClass(c, repo));

  return [header, packageClass, ...entityClasses].join("\n\n") + "\n";
}

function emitPackageClass(
  className: string,
  concepts: readonly NodeId[],
  taxonomies: readonly NodeId[],
  repo: Repository,
): string
{
  const cases = concepts.map((c) => `      case "${c}": return new ${pascalCase(c)}(this, id);`).join("\n");
  const createEntity =
    `  protected override createEntity(id: string): EntityBase {\n` +
    `    switch (this.resolve(id)?.type) {\n` +
    `${cases}\n` +
    `      default: return super.createEntity(id);\n` +
    `    }\n` +
    `  }`;

  const conceptGetters = concepts.map(
    (c) =>
      `  get ${pluralize(camelCase(c))}(): readonly ${pascalCase(c)}[] {\n` +
      `    return this.instancesOf("${c}").filter((id) => !this.isClass(id)).map((id) => this.entity(id) as ${pascalCase(c)});\n` +
      `  }`,
  );
  const taxonomyGetters = taxonomies.map((t) => {
    const rep = pascalCase(repo.represents(t)[0] ?? t);
    return (
      `  get ${camelCase(t)}(): readonly ${rep}[] {\n` +
      `    return this.termsOf("${t}").map((id) => this.entity(id) as ${rep});\n` +
      `  }`
    );
  });

  const authoring = concepts.map((c) => emitAuthoringConstructor(c, repo));
  const members = [...conceptGetters, ...taxonomyGetters, ...authoring].join("\n\n");
  return `export class ${className} extends FrozenRepository {\n${createEntity}\n\n${members}\n}`;
}

function emitAuthoringConstructor(concept: NodeId, repo: Repository): string
{
  const schema = repo.effectiveSchema(concept);

  const scalarFields = schema.fields
    .filter((f) => !isReferenceType(repo, f.type))
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  for (const f of scalarFields)
  {
    if (isMany(f.cardinality))
    {
      throw new Error(`Authoring codegen: ManyValued scalar field "${concept}.${f.name}" is unsupported`);
    }
  }

  const refMembers: RefMember[] = [
    ...schema.fields
      .filter((f) => isReferenceType(repo, f.type))
      .map((f) => ({ name: f.name, targetPascal: targetPascal(repo, f.type), many: isMany(f.cardinality) })),
    ...schema.relationships.map((r) => ({
      name: r.name,
      targetPascal: pascalCase(r.targets[0]!),
      many: isMany(r.cardinality),
    })),
  ].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

  const required = (card: Cardinality): boolean =>
    card === Cardinality.One || card === Cardinality.OneOrMore;
  const cardOf = (name: string): Cardinality => {
    const field = schema.fields.find((f) => f.name === name);
    if (field !== undefined) return field.cardinality;
    const rel = schema.relationships.find((r) => r.name === name);
    return rel?.cardinality ?? Cardinality.Optional;
  };

  const params: string[] = [];
  const assigns: string[] = [];

  for (const f of scalarFields)
  {
    const opt = required(f.cardinality) ? "" : "?";
    params.push(`    ${camelCase(f.name)}${opt}: ${scalarTsType(f.type)};`);
    const read = `fields.${camelCase(f.name)}`;
    assigns.push(
      required(f.cardinality)
        ? `    scalars.set("${f.name}", ${read});`
        : `    if (${read} !== undefined) scalars.set("${f.name}", ${read});`,
    );
  }

  for (const m of refMembers)
  {
    const opt = required(cardOf(m.name)) ? "" : "?";
    const type = m.many ? `readonly ${m.targetPascal}[]` : m.targetPascal;
    params.push(`    ${camelCase(m.name)}${opt}: ${type};`);
    const read = `fields.${camelCase(m.name)}`;
    const value = m.many ? `${read}.map((e) => e.id)` : `[${read}.id]`;
    assigns.push(
      required(cardOf(m.name))
        ? `    refs.set("${m.name}", ${value});`
        : `    if (${read} !== undefined) refs.set("${m.name}", ${value});`,
    );
  }

  return (
    `  ${camelCase(concept)}(id: string, fields: {\n` +
    `${params.join("\n")}\n` +
    `  }): InstanceDescriptor {\n` +
    `    const scalars = new Map<string, Scalar>();\n` +
    `    const refs = new Map<string, readonly NodeId[]>();\n` +
    `${assigns.join("\n")}\n` +
    `    return { concept: "${concept}", id, scalars, refs };\n` +
    `  }`
  );
}

function emitEntityClass(concept: NodeId, repo: Repository): string
{
  const schema = repo.effectiveSchema(concept);

  const scalarGetters = schema.fields
    .filter((f) => !isReferenceType(repo, f.type))
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
    .map((f) => {
      const ts = scalarTsType(f.type);
      return `  get ${camelCase(f.name)}(): ${ts} { return this.field("${f.name}") as ${ts}; }`;
    });

  const refMembers: RefMember[] = [
    ...schema.fields
      .filter((f) => isReferenceType(repo, f.type))
      .map((f) => ({ name: f.name, targetPascal: targetPascal(repo, f.type), many: isMany(f.cardinality) })),
    ...schema.relationships.map((r) => ({
      name: r.name,
      targetPascal: pascalCase(r.targets[0]!),
      many: isMany(r.cardinality),
    })),
  ].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

  const refGetters = refMembers.map((m) =>
    m.many
      ? `  get ${camelCase(m.name)}(): readonly ${m.targetPascal}[] { return this.refs("${m.name}") as ${m.targetPascal}[]; }`
      : `  get ${camelCase(m.name)}(): ${m.targetPascal} | undefined { return this.ref("${m.name}") as ${m.targetPascal} | undefined; }`,
  );

  const getters = [...scalarGetters, ...refGetters].join("\n");
  return `export class ${pascalCase(concept)} extends EntityBase {\n${getters}\n}`;
}
