// presentation.generated.mu — AUTOGENERATED. Do not edit.
// Regenerated from the compiled model. Author templates live in presentation/*.mu.

resources LibraryPresentation {

    // --- Icons: one geometry per distinct icon referenced by the model. ---
    include colored "resources/agent.svg" as mm_icon_agent
    include colored "resources/ai-builder.svg" as mm_icon_ai_builder
    include colored "resources/ai-foundry-agent-svc.svg" as mm_icon_ai_foundry_agent_svc
    include colored "resources/ai-red-teaming-agent.svg" as mm_icon_ai_red_teaming_agent
    include colored "resources/ai_search.svg" as mm_icon_ai_search
    include colored "resources/aks-edge-essentials.svg" as mm_icon_aks_edge_essentials
    include colored "resources/api-management.svg" as mm_icon_api_management
    include colored "resources/app-configuration.svg" as mm_icon_app_configuration
    include colored "resources/app-service.svg" as mm_icon_app_service
    include colored "resources/application-gateway.svg" as mm_icon_application_gateway
    include colored "resources/archive-storage.svg" as mm_icon_archive_storage
    include colored "resources/automation.svg" as mm_icon_automation
    include colored "resources/azure-advisor.svg" as mm_icon_azure_advisor
    include colored "resources/azure-ai-bot-service.svg" as mm_icon_azure_ai_bot_service
    include colored "resources/azure-ai-content-safety.svg" as mm_icon_azure_ai_content_safety
    include colored "resources/azure-ai-custom-vision.svg" as mm_icon_azure_ai_custom_vision
    include colored "resources/azure-ai-foundry-models.svg" as mm_icon_azure_ai_foundry_models
    include colored "resources/azure-ai-immersive-reader.svg" as mm_icon_azure_ai_immersive_reader
    include colored "resources/azure-ai-services.svg" as mm_icon_azure_ai_services
    include colored "resources/azure-ai-video-indexer.svg" as mm_icon_azure_ai_video_indexer
    include colored "resources/azure-analysis-services.svg" as mm_icon_azure_analysis_services
    include colored "resources/azure-api-for-fhir.svg" as mm_icon_azure_api_for_fhir
    include colored "resources/azure-app-testing.svg" as mm_icon_azure_app_testing
    include colored "resources/azure-arc.svg" as mm_icon_azure_arc
    include colored "resources/azure-artifacts.svg" as mm_icon_azure_artifacts
    include colored "resources/azure-backup.svg" as mm_icon_azure_backup
    include colored "resources/azure-blueprints.svg" as mm_icon_azure_blueprints
    include colored "resources/azure-boards.svg" as mm_icon_azure_boards
    include colored "resources/azure-cache-for-redis.svg" as mm_icon_azure_cache_for_redis
    include colored "resources/azure-chaos-studio.svg" as mm_icon_azure_chaos_studio
    include colored "resources/azure-cloud-shell.svg" as mm_icon_azure_cloud_shell
    include colored "resources/azure-communication-services.svg" as mm_icon_azure_communication_services
    include colored "resources/azure-compute-fleet.svg" as mm_icon_azure_compute_fleet
    include colored "resources/azure-confidential-ledger.svg" as mm_icon_azure_confidential_ledger
    include colored "resources/azure-container-apps.svg" as mm_icon_azure_container_apps
    include colored "resources/azure-container-instances.svg" as mm_icon_azure_container_instances
    include colored "resources/azure-container-registry.svg" as mm_icon_azure_container_registry
    include colored "resources/azure-container-storage.svg" as mm_icon_azure_container_storage
    include colored "resources/azure-content-understanding.svg" as mm_icon_azure_content_understanding
    include colored "resources/azure-copilot.svg" as mm_icon_azure_copilot
    include colored "resources/azure-cosmos-db.svg" as mm_icon_azure_cosmos_db
    include colored "resources/azure-cyclecloud.svg" as mm_icon_azure_cyclecloud
    include colored "resources/azure-data-box.svg" as mm_icon_azure_data_box
    include colored "resources/azure-data-explorer.svg" as mm_icon_azure_data_explorer
    include colored "resources/azure-data-factory.svg" as mm_icon_azure_data_factory
    include colored "resources/azure-data-lake-analytics.svg" as mm_icon_azure_data_lake_analytics
    include colored "resources/azure-data-lake-storage.svg" as mm_icon_azure_data_lake_storage
    include colored "resources/azure-data-manager-for-agriculture.svg" as mm_icon_azure_data_manager_for_agriculture
    include colored "resources/azure-data-manager-for-energy.svg" as mm_icon_azure_data_manager_for_energy
    include colored "resources/azure-data-share.svg" as mm_icon_azure_data_share
    include colored "resources/azure-database-for-mariadb.svg" as mm_icon_azure_database_for_mariadb
    include colored "resources/azure-database-for-mysql.svg" as mm_icon_azure_database_for_mysql
    include colored "resources/azure-database-for-postgresql.svg" as mm_icon_azure_database_for_postgresql
    include colored "resources/azure-database-migration-service.svg" as mm_icon_azure_database_migration_service
    include colored "resources/azure-databricks.svg" as mm_icon_azure_databricks
    include colored "resources/azure-ddos-protection.svg" as mm_icon_azure_ddos_protection
    include colored "resources/azure-dedicated-host.svg" as mm_icon_azure_dedicated_host
    include colored "resources/azure-dedicated-hsm.svg" as mm_icon_azure_dedicated_hsm
    include colored "resources/azure-deployment-environments.svg" as mm_icon_azure_deployment_environments
    include colored "resources/azure-devops.svg" as mm_icon_azure_devops
    include colored "resources/azure-devtest-labs.svg" as mm_icon_azure_devtest_labs
    include colored "resources/azure-digital-twins.svg" as mm_icon_azure_digital_twins
    include colored "resources/azure-disk-storage.svg" as mm_icon_azure_disk_storage
    include colored "resources/azure-dns.svg" as mm_icon_azure_dns
    include colored "resources/azure-document-intelligence.svg" as mm_icon_azure_document_intelligence
    include colored "resources/azure-documentdb.svg" as mm_icon_azure_documentdb
    include colored "resources/azure-elastic-san.svg" as mm_icon_azure_elastic_san
    include colored "resources/azure-expressroute.svg" as mm_icon_azure_expressroute
    include colored "resources/azure-face.svg" as mm_icon_azure_face
    include colored "resources/azure-files.svg" as mm_icon_azure_files
    include colored "resources/azure-firewall.svg" as mm_icon_azure_firewall
    include colored "resources/azure-fluid-relay.svg" as mm_icon_azure_fluid_relay
    include colored "resources/azure-front-door.svg" as mm_icon_azure_front_door
    include colored "resources/azure-functions.svg" as mm_icon_azure_functions
    include colored "resources/azure-health-data-services.svg" as mm_icon_azure_health_data_services
    include colored "resources/azure-information-protection.svg" as mm_icon_azure_information_protection
    include colored "resources/azure-iot-central.svg" as mm_icon_azure_iot_central
    include colored "resources/azure-iot-edge.svg" as mm_icon_azure_iot_edge
    include colored "resources/azure-iot-hub.svg" as mm_icon_azure_iot_hub
    include colored "resources/azure-iot-operations.svg" as mm_icon_azure_iot_operations
    include colored "resources/azure-iot.svg" as mm_icon_azure_iot
    include colored "resources/azure-key-vault.svg" as mm_icon_azure_key_vault
    include colored "resources/azure-kubernetes-fleet-manager.svg" as mm_icon_azure_kubernetes_fleet_manager
    include colored "resources/azure-kubernetes-service.svg" as mm_icon_azure_kubernetes_service
    include colored "resources/azure-lab-services.svg" as mm_icon_azure_lab_services
    include colored "resources/azure-language.svg" as mm_icon_azure_language
    include colored "resources/azure-lighthouse.svg" as mm_icon_azure_lighthouse
    include colored "resources/azure-local.svg" as mm_icon_azure_local
    include colored "resources/azure-logic-apps.svg" as mm_icon_azure_logic_apps
    include "resources/azure-machine-learning.png" as mm_icon_azure_machine_learning
    include colored "resources/azure-managed-applications.svg" as mm_icon_azure_managed_applications
    include colored "resources/azure-managed-instance-apache-cassandra.svg" as mm_icon_azure_managed_instance_apache_cassandra
    include colored "resources/azure-managed-lustre.svg" as mm_icon_azure_managed_lustre
    include colored "resources/azure-managed-redis.svg" as mm_icon_azure_managed_redis
    include colored "resources/azure-maps.svg" as mm_icon_azure_maps
    include colored "resources/azure-media-player.svg" as mm_icon_azure_media_player
    include colored "resources/azure-migrate.svg" as mm_icon_azure_migrate
    include colored "resources/azure-monitor.svg" as mm_icon_azure_monitor
    include colored "resources/azure-netapp-files.svg" as mm_icon_azure_netapp_files
    include colored "resources/azure-openai-service.svg" as mm_icon_azure_openai_service
    include colored "resources/azure-operator-nexus.svg" as mm_icon_azure_operator_nexus
    include colored "resources/azure-operator-service-manager.svg" as mm_icon_azure_operator_service_manager
    include colored "resources/azure-pipelines.svg" as mm_icon_azure_pipelines
    include colored "resources/azure-policy.svg" as mm_icon_azure_policy
    include colored "resources/azure-private-link.svg" as mm_icon_azure_private_link
    include colored "resources/azure-quantum.svg" as mm_icon_azure_quantum
    include colored "resources/azure-red-hat-openshift.svg" as mm_icon_azure_red_hat_openshift
    include colored "resources/azure-repos.svg" as mm_icon_azure_repos
    include colored "resources/azure-resource-manager.svg" as mm_icon_azure_resource_manager
    include colored "resources/azure-resource-mover.svg" as mm_icon_azure_resource_mover
    include colored "resources/azure-service-fabric.svg" as mm_icon_azure_service_fabric
    include colored "resources/azure-service-health.svg" as mm_icon_azure_service_health
    include colored "resources/azure-signalr-service.svg" as mm_icon_azure_signalr_service
    include colored "resources/azure-site-recovery.svg" as mm_icon_azure_site_recovery
    include colored "resources/azure-speech.svg" as mm_icon_azure_speech
    include colored "resources/azure-sphere.svg" as mm_icon_azure_sphere
    include colored "resources/azure-spot-virtual-machines.svg" as mm_icon_azure_spot_virtual_machines
    include colored "resources/azure-spring-apps.svg" as mm_icon_azure_spring_apps
    include colored "resources/azure-sql-database.svg" as mm_icon_azure_sql_database
    include colored "resources/azure-sql-managed-instance.svg" as mm_icon_azure_sql_managed_instance
    include colored "resources/azure-stack-edge.svg" as mm_icon_azure_stack_edge
    include colored "resources/azure-stack-hub.svg" as mm_icon_azure_stack_hub
    include colored "resources/azure-storage-actions.svg" as mm_icon_azure_storage_actions
    include colored "resources/azure-stream-analytics.svg" as mm_icon_azure_stream_analytics
    include colored "resources/azure-synapse-analytics.svg" as mm_icon_azure_synapse_analytics
    include colored "resources/azure-test-plans.svg" as mm_icon_azure_test_plans
    include colored "resources/azure-translator.svg" as mm_icon_azure_translator
    include colored "resources/azure-update-manager.svg" as mm_icon_azure_update_manager
    include colored "resources/azure-virtual-desktop.svg" as mm_icon_azure_virtual_desktop
    include colored "resources/azure-virtual-machines.svg" as mm_icon_azure_virtual_machines
    include colored "resources/azure-vision.svg" as mm_icon_azure_vision
    include colored "resources/azure-vmware-solution.svg" as mm_icon_azure_vmware_solution
    include colored "resources/azure-web-pubsub.svg" as mm_icon_azure_web_pubsub
    include colored "resources/azure_event_hub.svg" as mm_icon_azure_event_hub
    include colored "resources/azure_service_bus.svg" as mm_icon_azure_service_bus
    include colored "resources/azure_storage_blob.svg" as mm_icon_azure_storage_blob
    include colored "resources/batch.svg" as mm_icon_batch
    include colored "resources/cloud-services.svg" as mm_icon_cloud_services
    include colored "resources/content-protection.svg" as mm_icon_content_protection
    include colored "resources/copilot.svg" as mm_icon_copilot
    include colored "resources/copilotstudio.svg" as mm_icon_copilotstudio
    include colored "resources/cost-management-billing.svg" as mm_icon_cost_management_billing
    include colored "resources/data-science-vms.svg" as mm_icon_data_science_vms
    include colored "resources/dataverse.svg" as mm_icon_dataverse
    include colored "resources/dynamics-365-business-central.svg" as mm_icon_dynamics_365_business_central
    include colored "resources/dynamics-365-commerce.svg" as mm_icon_dynamics_365_commerce
    include colored "resources/dynamics-365-contact-center.svg" as mm_icon_dynamics_365_contact_center
    include colored "resources/dynamics-365-customer-insights.svg" as mm_icon_dynamics_365_customer_insights
    include colored "resources/dynamics-365-customer-service.svg" as mm_icon_dynamics_365_customer_service
    include colored "resources/dynamics-365-customer-voice.svg" as mm_icon_dynamics_365_customer_voice
    include colored "resources/dynamics-365-field-service.svg" as mm_icon_dynamics_365_field_service
    include colored "resources/dynamics-365-finance.svg" as mm_icon_dynamics_365_finance
    include colored "resources/dynamics-365-human-resources.svg" as mm_icon_dynamics_365_human_resources
    include colored "resources/dynamics-365-intelligent-order-management.svg" as mm_icon_dynamics_365_intelligent_order_management
    include colored "resources/dynamics-365-project-operations.svg" as mm_icon_dynamics_365_project_operations
    include colored "resources/dynamics-365-remote-assist.svg" as mm_icon_dynamics_365_remote_assist
    include colored "resources/dynamics-365-sales.svg" as mm_icon_dynamics_365_sales
    include colored "resources/dynamics-365-supply-chain-management.svg" as mm_icon_dynamics_365_supply_chain_management
    include colored "resources/dynamics365.svg" as mm_icon_dynamics365
    include colored "resources/encoding.svg" as mm_icon_encoding
    include colored "resources/event-grid.svg" as mm_icon_event_grid
    include colored "resources/event-hubs.svg" as mm_icon_event_hubs
    include colored "resources/exchange-online.svg" as mm_icon_exchange_online
    include "resources/fabric-data-engineering.png" as mm_icon_fabric_data_engineering
    include "resources/fabric-data-factory.png" as mm_icon_fabric_data_factory
    include "resources/fabric-data-science.png" as mm_icon_fabric_data_science
    include "resources/fabric-data-warehouse.png" as mm_icon_fabric_data_warehouse
    include colored "resources/fabric-databases.svg" as mm_icon_fabric_databases
    include colored "resources/fabric-iq.svg" as mm_icon_fabric_iq
    include "resources/fabric-real-time-intelligence.png" as mm_icon_fabric_real_time_intelligence
    include colored "resources/fabric.svg" as mm_icon_fabric
    include colored "resources/foundry-control-plane.svg" as mm_icon_foundry_control_plane
    include "resources/foundry-local.png" as mm_icon_foundry_local
    include "resources/foundry-models.png" as mm_icon_foundry_models
    include colored "resources/foundry-tools.svg" as mm_icon_foundry_tools
    include colored "resources/hdinsight.svg" as mm_icon_hdinsight
    include colored "resources/health-bot.svg" as mm_icon_health_bot
    include colored "resources/live-on-demand-streaming.svg" as mm_icon_live_on_demand_streaming
    include colored "resources/llm.svg" as mm_icon_llm
    include colored "resources/load-balancer.svg" as mm_icon_load_balancer
    include colored "resources/media-services.svg" as mm_icon_media_services
    include colored "resources/microsoft-365-archive.svg" as mm_icon_microsoft_365_archive
    include colored "resources/microsoft-365-backup.svg" as mm_icon_microsoft_365_backup
    include colored "resources/microsoft-azure-portal.svg" as mm_icon_microsoft_azure_portal
    include colored "resources/microsoft-bookings.svg" as mm_icon_microsoft_bookings
    include colored "resources/microsoft-clipchamp.svg" as mm_icon_microsoft_clipchamp
    include colored "resources/microsoft-defender-easm.svg" as mm_icon_microsoft_defender_easm
    include colored "resources/microsoft-defender-for-cloud.svg" as mm_icon_microsoft_defender_for_cloud
    include colored "resources/microsoft-defender-for-iot.svg" as mm_icon_microsoft_defender_for_iot
    include colored "resources/microsoft-dev-box.svg" as mm_icon_microsoft_dev_box
    include "resources/microsoft-entra-agent-id.png" as mm_icon_microsoft_entra_agent_id
    include colored "resources/microsoft-entra-domain-services.svg" as mm_icon_microsoft_entra_domain_services
    include colored "resources/microsoft-entra-external-id.svg" as mm_icon_microsoft_entra_external_id
    include "resources/microsoft-entra-id-governance.png" as mm_icon_microsoft_entra_id_governance
    include "resources/microsoft-entra-id-protection.png" as mm_icon_microsoft_entra_id_protection
    include colored "resources/microsoft-entra-id.svg" as mm_icon_microsoft_entra_id
    include "resources/microsoft-entra-internet-access.png" as mm_icon_microsoft_entra_internet_access
    include "resources/microsoft-entra-private-access.png" as mm_icon_microsoft_entra_private_access
    include "resources/microsoft-entra-verified-id.png" as mm_icon_microsoft_entra_verified_id
    include "resources/microsoft-entra-workload-id.png" as mm_icon_microsoft_entra_workload_id
    include colored "resources/microsoft-forms.svg" as mm_icon_microsoft_forms
    include "resources/microsoft-foundry.png" as mm_icon_microsoft_foundry
    include colored "resources/microsoft-intune.svg" as mm_icon_microsoft_intune
    include colored "resources/microsoft-playwright-testing.svg" as mm_icon_microsoft_playwright_testing
    include colored "resources/microsoft-purview.svg" as mm_icon_microsoft_purview
    include colored "resources/microsoft-sentinel.svg" as mm_icon_microsoft_sentinel
    include colored "resources/microsoft-viva-engage.svg" as mm_icon_microsoft_viva_engage
    include "resources/microsoft-whiteboard.png" as mm_icon_microsoft_whiteboard
    include colored "resources/microsoft_graph.svg" as mm_icon_microsoft_graph
    include colored "resources/nat-gateway.svg" as mm_icon_nat_gateway
    include colored "resources/notification-hubs.svg" as mm_icon_notification_hubs
    include colored "resources/onedrive.svg" as mm_icon_onedrive
    include colored "resources/onelake.svg" as mm_icon_onelake
    include colored "resources/planner.svg" as mm_icon_planner
    include colored "resources/power-apps.svg" as mm_icon_power_apps
    include colored "resources/power-bi-embedded.svg" as mm_icon_power_bi_embedded
    include colored "resources/power-pages.svg" as mm_icon_power_pages
    include colored "resources/power_automate.svg" as mm_icon_power_automate
    include colored "resources/power_bi.svg" as mm_icon_power_bi
    include colored "resources/queue-storage.svg" as mm_icon_queue_storage
    include colored "resources/sharepoint_online.svg" as mm_icon_sharepoint_online
    include colored "resources/sql-server-on-vms.svg" as mm_icon_sql_server_on_vms
    include colored "resources/sql.svg" as mm_icon_sql
    include colored "resources/static-web-apps.svg" as mm_icon_static_web_apps
    include colored "resources/storage-explorer.svg" as mm_icon_storage_explorer
    include colored "resources/table-storage.svg" as mm_icon_table_storage
    include colored "resources/teams.svg" as mm_icon_teams
    include colored "resources/virtual-machine-scale-sets.svg" as mm_icon_virtual_machine_scale_sets
    include colored "resources/virtual-network.svg" as mm_icon_virtual_network
    include colored "resources/virtual-wan.svg" as mm_icon_virtual_wan
    include colored "resources/vpn-gateway.svg" as mm_icon_vpn_gateway
    include colored "resources/web-app-for-containers.svg" as mm_icon_web_app_for_containers
    include colored "resources/web-application-firewall.svg" as mm_icon_web_application_firewall
    include colored "resources/windows-10-iot-core-services.svg" as mm_icon_windows_10_iot_core_services
    include colored "resources/windows-for-iot.svg" as mm_icon_windows_for_iot

    // --- Embedded content (base64) — reserved for future assets. ---
}
