// presentation.generated.mu — AUTOGENERATED. Do not edit.
// Regenerated from the compiled model. Author templates live in presentation/*.mu.

resources MetaModelPresentation {

    // --- Icons: one geometry per distinct icon referenced by the model. ---
    include colored "resources/ai-agent.svg" as mm_icon_ai_agent
    include colored "resources/analytical-store.svg" as mm_icon_analytical_store
    include colored "resources/api-service.svg" as mm_icon_api_service
    include colored "resources/authorization-service.svg" as mm_icon_authorization_service
    include colored "resources/cache.svg" as mm_icon_cache
    include colored "resources/chatbot.svg" as mm_icon_chatbot
    include colored "resources/conversational-interface.svg" as mm_icon_conversational_interface
    include colored "resources/desktop-app.svg" as mm_icon_desktop_app
    include colored "resources/document-store.svg" as mm_icon_document_store
    include colored "resources/embedded-widget.svg" as mm_icon_embedded_widget
    include colored "resources/enterprise-api-catalogue.svg" as mm_icon_enterprise_api_catalogue
    include colored "resources/event-log.svg" as mm_icon_event_log
    include colored "resources/event-processor.svg" as mm_icon_event_processor
    include colored "resources/federated-identity-provider.svg" as mm_icon_federated_identity_provider
    include colored "resources/file-store.svg" as mm_icon_file_store
    include colored "resources/gear.svg" as mm_icon_gear
    include colored "resources/integration-adapter.svg" as mm_icon_integration_adapter
    include colored "resources/internal-api-gateway.svg" as mm_icon_internal_api_gateway
    include colored "resources/knowledge-source.svg" as mm_icon_knowledge_source
    include colored "resources/language-model.svg" as mm_icon_language_model
    include colored "resources/legacy_application.svg" as mm_icon_legacy_application
    include colored "resources/message-queue.svg" as mm_icon_message_queue
    include colored "resources/message-topic.svg" as mm_icon_message_topic
    include colored "resources/mobile-app.svg" as mm_icon_mobile_app
    include colored "resources/notification-service.svg" as mm_icon_notification_service
    include colored "resources/orchestration-engine.svg" as mm_icon_orchestration_engine
    include colored "resources/partner-integration-endpoint.svg" as mm_icon_partner_integration_endpoint
    include colored "resources/public-api.svg" as mm_icon_public_api
    include colored "resources/public-mcp-server.svg" as mm_icon_public_mcp_server
    include colored "resources/rag.svg" as mm_icon_rag
    include colored "resources/relational-store.svg" as mm_icon_relational_store
    include colored "resources/reporting-surface.svg" as mm_icon_reporting_surface
    include colored "resources/scenario.svg" as mm_icon_scenario
    include colored "resources/scheduler.svg" as mm_icon_scheduler
    include colored "resources/semantic-index.svg" as mm_icon_semantic_index
    include colored "resources/service.svg" as mm_icon_service
    include colored "resources/validator.svg" as mm_icon_validator
    include colored "resources/web-portal.svg" as mm_icon_web_portal
    include colored "resources/workflow-engine.svg" as mm_icon_workflow_engine

    // --- Embedded content (base64) — reserved for future assets. ---
}
