import { MetaKind } from "../../../compiler-services/model/kinds.js";
import type { Repository } from "../../../compiler-services/model/model.js";
import { camelCase, pascalCase, pluralize } from "../../../codegen/naming.js";

// Builds `generated/app.mu` (spec §per-project-app-build, task 2): the default
// application-UI markup for a compiled model — one section per concept, each a
// ListBox bound (via mural's `$path` DataContextBinding syntax) to the SAME
// collection accessor name `generateReadClient` (../../../codegen/read-client.ts)
// puts on the generated DTO package class — pluralize(camelCase(conceptId)) —
// so the emitted markup wires straight onto the DTO instance the bootstrap
// assigns as the root visual's DataContext. The root visual carries `x:root`
// inside the Application's `resources:` slot, which mural's compiler lowers to
// `Resources.Root = <visual>` — the Application's content extension point.
export class AppUiTemplate
{
    // First line of every emitted file. Historically GenerateAppUiAction's clobber
    // guard compared an existing file's first line against this constant to tell
    // regenerable output from a hand-edited file; the guard has since moved —
    // UiPlaceholderGenerator (project-services/generators/) writes generated/app.mu
    // WriteOnce and never touches a file that already exists, so no marker check is
    // needed there. The marker still stamps the file's first line as an at-a-glance
    // "this was generated" signal for anyone reading it by hand.
    public static readonly GeneratedMarker = "// @generated by todl build — regenerable";

    private static readonly HeaderComment =
        "// generated/app.mu — default application UI, generated once as a placeholder.\n" +
        "// Safe to edit: remove the marker line above to author this file by hand instead.";

    private static readonly ApplicationOpen = "Application {";
    private static readonly ResourcesOpen = "    resources: {";
    private static readonly RootOpen = "        StackPanel x:root [ Orientation = Vertical, Margin = (12,12,12,12) ] {";
    private static readonly RootClose = "        }";
    private static readonly ResourcesClose = "    }";
    private static readonly ApplicationClose = "}";

    private static readonly EmptyStateLine =
        "            TextBlock [ Text = \"This model has no concepts yet.\", FontSize = 13 ]";

    private static readonly SectionHeaderPlaceholder = "__HEADER__";
    private static readonly SectionCollectionPlaceholder = "__COLLECTION__";
    private static readonly SectionIdPropertyName = "id";
    private static readonly SectionTemplate =
        "            StackPanel [ Orientation = Vertical, Margin = (0,0,0,16) ] {\n" +
        `                TextBlock [ Text = "${AppUiTemplate.SectionHeaderPlaceholder}", FontSize = 15, FontWeight = Bold, Margin = (0,0,0,4) ]\n` +
        `                ListBox [ ItemsSource = $${AppUiTemplate.SectionCollectionPlaceholder}, DisplayMemberPath = "${AppUiTemplate.SectionIdPropertyName}" ]\n` +
        "            }";

    public static Render(repo: Repository): string
    {
        const conceptIds = AppUiTemplate.ConceptIds(repo);
        const sections = conceptIds.length === 0
            ? AppUiTemplate.EmptyStateLine
            : conceptIds.map((id) => AppUiTemplate.RenderSection(id)).join("\n\n");

        return [
            AppUiTemplate.GeneratedMarker,
            AppUiTemplate.HeaderComment,
            "",
            AppUiTemplate.ApplicationOpen,
            AppUiTemplate.ResourcesOpen,
            AppUiTemplate.RootOpen,
            sections,
            AppUiTemplate.RootClose,
            AppUiTemplate.ResourcesClose,
            AppUiTemplate.ApplicationClose,
            "",
        ].join("\n");
    }

    // Same enumeration + sort order as generateReadClient's `concepts` list
    // (read-client.ts) — determinism matters here only for diff-stability,
    // but matching it exactly keeps the two generators easy to reason about
    // side by side.
    private static ConceptIds(repo: Repository): readonly string[]
    {
        return repo
            .allNodes()
            .filter((n) => n.metaKind === MetaKind.Concept)
            .map((n) => n.id)
            .sort();
    }

    // Collection accessor name MUST equal generateReadClient's `emitPackageClass`
    // conceptGetters name — `pluralize(camelCase(conceptId))` — so the `$path`
    // binding below resolves against the generated DTO instance.
    private static RenderSection(conceptId: string): string
    {
        const collection = pluralize(camelCase(conceptId));
        const header = pascalCase(conceptId);
        return AppUiTemplate.SectionTemplate
            .replace(AppUiTemplate.SectionHeaderPlaceholder, header)
            .replace(AppUiTemplate.SectionCollectionPlaceholder, collection);
    }
}
